// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// maybe someone find a better solution. For now this is more than a workaround.
//
package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var ComputeResourceEndpointPrefix = fmt.Sprintf("%s", strings.ToLower("Compute_resources"))

type QueryResponseComputeResource struct {
	QueryResponse
	Results []ComputeResource `json:"results"`
}

func (c *Client) GetComputeResource(ctx context.Context, idOrName string) (*ComputeResource, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetComputeResourceByID(ctx, int(id))
	}
	return c.GetComputeResourceByName(ctx, idOrName)
}

func (c *Client) GetComputeResourceByID(ctx context.Context, id int) (*ComputeResource, error) {
	response := new(ComputeResource)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", ComputeResourceEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetComputeResourceByName(ctx context.Context, name string) (*ComputeResource, error) {
	response := new(QueryResponseComputeResource)
	filter := fmt.Sprintf("%s=\"%s\"", strings.ToLower("Name"), name)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", ComputeResourceEndpointPrefix), http.MethodGet, filter, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("ComputeResource not found")

	}
	return &response.Results[0], err
}

func (c *Client) ListComputeResource(ctx context.Context) (*QueryResponseComputeResource, error) {
	response := new(QueryResponseComputeResource)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", ComputeResourceEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) SearchComputeResource(ctx context.Context, filter string) (*QueryResponseComputeResource, error) {
	response := new(QueryResponseComputeResource)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", ComputeResourceEndpointPrefix), http.MethodGet, filter, nil, response)
	return response, err
}

func (c *Client) CreateComputeResource(ctx context.Context, createRequest interface{}) (*ComputeResource, error) {
	response := new(ComputeResource)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", ComputeResourceEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteComputeResource(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", ComputeResourceEndpointPrefix, id), http.MethodDelete, nil, nil)
}
