// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// maybe someone find a better solution. For now this is more than a workaround.
//
package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var ComputeProfileEndpointPrefix = fmt.Sprintf("%s", strings.ToLower("Compute_profiles"))

type QueryResponseComputeProfile struct {
	QueryResponse
	Results []ComputeProfile `json:"results"`
}

func (c *Client) GetComputeProfile(ctx context.Context, idOrName string) (*ComputeProfile, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetComputeProfileByID(ctx, int(id))
	}
	return c.GetComputeProfileByName(ctx, idOrName)
}

func (c *Client) GetComputeProfileByID(ctx context.Context, id int) (*ComputeProfile, error) {
	response := new(ComputeProfile)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", ComputeProfileEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetComputeProfileByName(ctx context.Context, name string) (*ComputeProfile, error) {
	response := new(QueryResponseComputeProfile)
	filter := fmt.Sprintf("%s=\"%s\"", strings.ToLower("Name"), name)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", ComputeProfileEndpointPrefix), http.MethodGet, filter, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("ComputeProfile not found")

	}
	return &response.Results[0], err
}

func (c *Client) ListComputeProfile(ctx context.Context) (*QueryResponseComputeProfile, error) {
	response := new(QueryResponseComputeProfile)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", ComputeProfileEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) SearchComputeProfile(ctx context.Context, filter string) (*QueryResponseComputeProfile, error) {
	response := new(QueryResponseComputeProfile)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", ComputeProfileEndpointPrefix), http.MethodGet, filter, nil, response)
	return response, err
}

func (c *Client) CreateComputeProfile(ctx context.Context, createRequest interface{}) (*ComputeProfile, error) {
	response := new(ComputeProfile)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", ComputeProfileEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteComputeProfile(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", ComputeProfileEndpointPrefix, id), http.MethodDelete, nil, nil)
}
