// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var DomainEndpointPrefix = fmt.Sprintf("%ss", strings.ToLower("Domain"))

type QueryResponseDomain struct {
	QueryResponse
	Results []Domain `json:"results"`
}

func (c *Client) GetDomain(ctx context.Context, idOrName string) (*Domain, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetDomainByID(ctx, int(id))
	}
	return c.GetDomainByName(ctx, idOrName)
}

func (c *Client) GetDomainByID(ctx context.Context, id int) (*Domain, error) {
	response := new(Domain)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", DomainEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetDomainByName(ctx context.Context, name string) (*Domain, error) {
	response := new(QueryResponseDomain)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", DomainEndpointPrefix), http.MethodGet, "name", name, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("Domain not found: %s", name)

	}
	return &response.Results[0], err
}

func (c *Client) ListDomain(ctx context.Context) (*QueryResponseDomain, error) {
	response := new(QueryResponseDomain)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", DomainEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) CreateDomain(ctx context.Context, createRequest interface{}) (*Domain, error) {
	response := new(Domain)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", DomainEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteDomain(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", DomainEndpointPrefix, id), http.MethodDelete, nil, nil)
}
