// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// maybe someone find a better solution. For now this is more than a workaround.
//
package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var EnvironmentEndpointPrefix = fmt.Sprintf("%s", strings.ToLower("Environments"))

type QueryResponseEnvironment struct {
	QueryResponse
	Results []Environment `json:"results"`
}

func (c *Client) GetEnvironment(ctx context.Context, idOrName string) (*Environment, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetEnvironmentByID(ctx, int(id))
	}
	return c.GetEnvironmentByName(ctx, idOrName)
}

func (c *Client) GetEnvironmentByID(ctx context.Context, id int) (*Environment, error) {
	response := new(Environment)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", EnvironmentEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetEnvironmentByName(ctx context.Context, name string) (*Environment, error) {
	response := new(QueryResponseEnvironment)
	filter := fmt.Sprintf("%s=\"%s\"", strings.ToLower("Name"), name)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", EnvironmentEndpointPrefix), http.MethodGet, filter, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("Environment not found")

	}
	return &response.Results[0], err
}

func (c *Client) ListEnvironment(ctx context.Context) (*QueryResponseEnvironment, error) {
	response := new(QueryResponseEnvironment)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", EnvironmentEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) SearchEnvironment(ctx context.Context, filter string) (*QueryResponseEnvironment, error) {
	response := new(QueryResponseEnvironment)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", EnvironmentEndpointPrefix), http.MethodGet, filter, nil, response)
	return response, err
}

func (c *Client) CreateEnvironment(ctx context.Context, createRequest interface{}) (*Environment, error) {
	response := new(Environment)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", EnvironmentEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteEnvironment(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", EnvironmentEndpointPrefix, id), http.MethodDelete, nil, nil)
}
