// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// maybe someone find a better solution. For now this is more than a workaround.
//
package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var ModelEndpointPrefix = fmt.Sprintf("%s", strings.ToLower("Models"))

type QueryResponseModel struct {
	QueryResponse
	Results []Model `json:"results"`
}

func (c *Client) GetModel(ctx context.Context, idOrName string) (*Model, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetModelByID(ctx, int(id))
	}
	return c.GetModelByName(ctx, idOrName)
}

func (c *Client) GetModelByID(ctx context.Context, id int) (*Model, error) {
	response := new(Model)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", ModelEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetModelByName(ctx context.Context, name string) (*Model, error) {
	response := new(QueryResponseModel)
	filter := fmt.Sprintf("%s=\"%s\"", strings.ToLower("Name"), name)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", ModelEndpointPrefix), http.MethodGet, filter, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("Model not found")

	}
	return &response.Results[0], err
}

func (c *Client) ListModel(ctx context.Context) (*QueryResponseModel, error) {
	response := new(QueryResponseModel)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", ModelEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) SearchModel(ctx context.Context, filter string) (*QueryResponseModel, error) {
	response := new(QueryResponseModel)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", ModelEndpointPrefix), http.MethodGet, filter, nil, response)
	return response, err
}

func (c *Client) CreateModel(ctx context.Context, createRequest interface{}) (*Model, error) {
	response := new(Model)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", ModelEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteModel(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", ModelEndpointPrefix, id), http.MethodDelete, nil, nil)
}
