// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// maybe someone find a better solution. For now this is more than a workaround.
//
package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var OrganizationEndpointPrefix = fmt.Sprintf("%s", strings.ToLower("Organizations"))

type QueryResponseOrganization struct {
	QueryResponse
	Results []Organization `json:"results"`
}

func (c *Client) GetOrganization(ctx context.Context, idOrName string) (*Organization, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetOrganizationByID(ctx, int(id))
	}
	return c.GetOrganizationByName(ctx, idOrName)
}

func (c *Client) GetOrganizationByID(ctx context.Context, id int) (*Organization, error) {
	response := new(Organization)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", OrganizationEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetOrganizationByName(ctx context.Context, name string) (*Organization, error) {
	response := new(QueryResponseOrganization)
	filter := fmt.Sprintf("%s=\"%s\"", strings.ToLower("Name"), name)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", OrganizationEndpointPrefix), http.MethodGet, filter, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("Organization not found")

	}
	return &response.Results[0], err
}

func (c *Client) ListOrganization(ctx context.Context) (*QueryResponseOrganization, error) {
	response := new(QueryResponseOrganization)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", OrganizationEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) SearchOrganization(ctx context.Context, filter string) (*QueryResponseOrganization, error) {
	response := new(QueryResponseOrganization)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", OrganizationEndpointPrefix), http.MethodGet, filter, nil, response)
	return response, err
}

func (c *Client) CreateOrganization(ctx context.Context, createRequest interface{}) (*Organization, error) {
	response := new(Organization)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", OrganizationEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteOrganization(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", OrganizationEndpointPrefix, id), http.MethodDelete, nil, nil)
}
