// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// maybe someone find a better solution. For now this is more than a workaround.
//
package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var OperatingSystemEndpointPrefix = fmt.Sprintf("%s", strings.ToLower("Operatingsystems"))

type QueryResponseOperatingSystem struct {
	QueryResponse
	Results []OperatingSystem `json:"results"`
}

func (c *Client) GetOperatingSystem(ctx context.Context, idOrName string) (*OperatingSystem, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetOperatingSystemByID(ctx, int(id))
	}
	return c.GetOperatingSystemByName(ctx, idOrName)
}

func (c *Client) GetOperatingSystemByID(ctx context.Context, id int) (*OperatingSystem, error) {
	response := new(OperatingSystem)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", OperatingSystemEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetOperatingSystemByName(ctx context.Context, name string) (*OperatingSystem, error) {
	response := new(QueryResponseOperatingSystem)
	filter := fmt.Sprintf("%s=\"%s\"", strings.ToLower("Title"), name)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", OperatingSystemEndpointPrefix), http.MethodGet, filter, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("OperatingSystem not found")

	}
	return &response.Results[0], err
}

func (c *Client) ListOperatingSystem(ctx context.Context) (*QueryResponseOperatingSystem, error) {
	response := new(QueryResponseOperatingSystem)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", OperatingSystemEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) SearchOperatingSystem(ctx context.Context, filter string) (*QueryResponseOperatingSystem, error) {
	response := new(QueryResponseOperatingSystem)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", OperatingSystemEndpointPrefix), http.MethodGet, filter, nil, response)
	return response, err
}

func (c *Client) CreateOperatingSystem(ctx context.Context, createRequest interface{}) (*OperatingSystem, error) {
	response := new(OperatingSystem)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", OperatingSystemEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteOperatingSystem(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", OperatingSystemEndpointPrefix, id), http.MethodDelete, nil, nil)
}
