// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// maybe someone find a better solution. For now this is more than a workaround.
//
package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var SmartProxyEndpointPrefix = fmt.Sprintf("%s", strings.ToLower("Smart_proxies"))

type QueryResponseSmartProxy struct {
	QueryResponse
	Results []SmartProxy `json:"results"`
}

func (c *Client) GetSmartProxy(ctx context.Context, idOrName string) (*SmartProxy, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetSmartProxyByID(ctx, int(id))
	}
	return c.GetSmartProxyByName(ctx, idOrName)
}

func (c *Client) GetSmartProxyByID(ctx context.Context, id int) (*SmartProxy, error) {
	response := new(SmartProxy)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", SmartProxyEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetSmartProxyByName(ctx context.Context, name string) (*SmartProxy, error) {
	response := new(QueryResponseSmartProxy)
	filter := fmt.Sprintf("%s=\"%s\"", strings.ToLower("Name"), name)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", SmartProxyEndpointPrefix), http.MethodGet, filter, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("SmartProxy not found")

	}
	return &response.Results[0], err
}

func (c *Client) ListSmartProxy(ctx context.Context) (*QueryResponseSmartProxy, error) {
	response := new(QueryResponseSmartProxy)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", SmartProxyEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) SearchSmartProxy(ctx context.Context, filter string) (*QueryResponseSmartProxy, error) {
	response := new(QueryResponseSmartProxy)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", SmartProxyEndpointPrefix), http.MethodGet, filter, nil, response)
	return response, err
}

func (c *Client) CreateSmartProxy(ctx context.Context, createRequest interface{}) (*SmartProxy, error) {
	response := new(SmartProxy)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", SmartProxyEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteSmartProxy(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", SmartProxyEndpointPrefix, id), http.MethodDelete, nil, nil)
}
