// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// maybe someone find a better solution. For now this is more than a workaround.
//
package foreman

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var SmartClassParameterEndpointPrefix = fmt.Sprintf("%s", strings.ToLower("Smart_class_parameters"))

type QueryResponseSmartClassParameter struct {
	QueryResponse
	Results []SmartClassParameter `json:"results"`
}

func (c *Client) GetSmartClassParameter(ctx context.Context, idOrName string) (*SmartClassParameter, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetSmartClassParameterByID(ctx, int(id))
	}
	return c.GetSmartClassParameterByName(ctx, idOrName)
}

func (c *Client) GetSmartClassParameterByID(ctx context.Context, id int) (*SmartClassParameter, error) {
	response := new(SmartClassParameter)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s/%d", SmartClassParameterEndpointPrefix, id), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) GetSmartClassParameterByName(ctx context.Context, name string) (*SmartClassParameter, error) {
	response := new(QueryResponseSmartClassParameter)
	filter := fmt.Sprintf("%s=\"%s\"", strings.ToLower("Puppetclass_name"), name)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", SmartClassParameterEndpointPrefix), http.MethodGet, filter, nil, response)
	if err != nil {
		return nil, err
	}
	if len(response.Results) == 0 {
		return nil, fmt.Errorf("SmartClassParameter not found")

	}
	return &response.Results[0], err
}

func (c *Client) ListSmartClassParameter(ctx context.Context) (*QueryResponseSmartClassParameter, error) {
	response := new(QueryResponseSmartClassParameter)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", SmartClassParameterEndpointPrefix), http.MethodGet, nil, response)
	return response, err
}

func (c *Client) SearchSmartClassParameter(ctx context.Context, filter string) (*QueryResponseSmartClassParameter, error) {
	response := new(QueryResponseSmartClassParameter)
	err := c.requestSearchHelper(ctx, fmt.Sprintf("/%s", SmartClassParameterEndpointPrefix), http.MethodGet, filter, nil, response)
	return response, err
}

func (c *Client) CreateSmartClassParameter(ctx context.Context, createRequest interface{}) (*SmartClassParameter, error) {
	response := new(SmartClassParameter)
	err := c.requestHelper(ctx, fmt.Sprintf("/%s", SmartClassParameterEndpointPrefix), http.MethodPost, createRequest, response)
	return response, err
}

func (c *Client) DeleteSmartClassParameter(ctx context.Context, id int) error {
	return c.requestHelper(ctx, fmt.Sprintf("/%s/%d", SmartClassParameterEndpointPrefix, id), http.MethodDelete, nil, nil)
}
