name: Build
on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Verify & download dependencies
      run: |
        go mod verify
        go mod download

    - name: Run go fmt
      run: diff -u <(echo -n) <(gofmt -d -s .)

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -v ./...

    - name: Build
      run: go build
